name: Run tests

on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    tests:
        strategy:
            matrix:
                os: [Ubuntu, Windows, macOS]
                php: [7.3, 7.4, 8.0]
                # php: [7.2, 7.3, 7.4, 8.0]

                include:
                  - os: Ubuntu
                    os-version: ubuntu-latest

                  - os: Windows
                    os-version: windows-latest

                  - os: macOS
                    os-version: macos-latest

                  - os: macOS-11
                    os-version: macos-11.0
                    php: 8.0

        name: ${{ matrix.os }} - PHP ${{ matrix.php }}

        runs-on: ${{ matrix.os-version }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            # - name: Cache dependencies
            #   uses: actions/cache@v1
            #   with:
            #       path: ~/.composer/cache/files
            #       key: dependencies-os-${{ matrix.os }}-php-${{ matrix.php }}-laravel-${{ matrix.laravel-version }}-composer-${{ hashFiles('**/composer.lock') }}
            #       restore-keys: dependencies-os-${{ matrix.os }}-php-${{ matrix.php }}-laravel-${{ matrix.laravel-version }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Install dependencies
              run: composer update --prefer-stable --prefer-dist --no-interaction --no-suggest --ignore-platform-reqs

            - name: Run tests
              run: vendor/bin/phpunit

            - name: Send Slack notification
              uses: 8398a7/action-slack@v2
              if: failure()
              with:
                  status: ${{ job.status }}
                  author_name: ${{ github.actor }}
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
